### ISSUE TITLE
so....how do i update ebot when there's are new update + how to open ebot again if i restarted the vps

### ISSUE THREAD

**Issue by wavypzuto** [Flegma/ebot-cs2-install-script#5]
so....how do i update ebot when there's are new update + how to open ebot again if i restarted the vps

**Comment by Flegma** [comment]
Currently there is no way to update ebot with this script, you can only run it once again and get new version from DestrO's GitHub. 
If you restart VPS you should have knowledge how to run processes in screen (so that it continues to run in background) - until i make a service for the ebot app and logs processes.

**Comment by wavypzuto** [comment]
thanks man, really appriciate your works, have a nice day!
